-- Client changes "Änderungen 15062026" (15 June 2026) — dev DB, data only, idempotent.
-- Covers: #1 Stadtvilla 22-157 grey hero image, #2 Stadtvilla 22-166 heading,
-- #6 Fellbach contact order, #9 Nittel contact (Gabriella Schaffer),
-- #10 de-hyphenated house descriptions (23 models). Safe to re-run.
--> statement-breakpoint
-- #1 grey image media row
INSERT INTO "boholz"."media" ("path", "width", "height")
SELECT '/images/models/stadtvilla/22-157/gallery/stadtvilla-22-157-gallery-sv-157-22-0-grau.webp', 2400, 1697
WHERE NOT EXISTS (SELECT 1 FROM "boholz"."media" WHERE "path" = '/images/models/stadtvilla/22-157/gallery/stadtvilla-22-157-gallery-sv-157-22-0-grau.webp');
--> statement-breakpoint
-- #1 grey image as hero+thumbnail (sort 0) for stadtvilla-22-157
INSERT INTO "boholz"."model_media" ("model_id", "media_id", "is_hero", "is_thumbnail", "sort_order")
SELECT '8945ad8d-411e-47b2-ad56-3356399f759d', (SELECT "id" FROM "boholz"."media" WHERE "path" = '/images/models/stadtvilla/22-157/gallery/stadtvilla-22-157-gallery-sv-157-22-0-grau.webp'), true, true, 0
WHERE NOT EXISTS (
  SELECT 1 FROM "boholz"."model_media"
  WHERE "model_id" = '8945ad8d-411e-47b2-ad56-3356399f759d' AND "media_id" = (SELECT "id" FROM "boholz"."media" WHERE "path" = '/images/models/stadtvilla/22-157/gallery/stadtvilla-22-157-gallery-sv-157-22-0-grau.webp')
);
--> statement-breakpoint
-- #1 demote current wood hero to 2nd image (must clear is_thumbnail so the gallery shows it)
UPDATE "boholz"."model_media" SET "is_hero" = false, "is_thumbnail" = false, "sort_order" = 1
WHERE "model_id" = '8945ad8d-411e-47b2-ad56-3356399f759d' AND "media_id" = '1ed1741e-2cf8-44c1-bafd-26405d3cb0fd';
--> statement-breakpoint
-- #1 push the stock images after the wood render
UPDATE "boholz"."model_media" SET "sort_order" = 2 WHERE "model_id" = '8945ad8d-411e-47b2-ad56-3356399f759d' AND "media_id" = 'da767643-a1a9-42c2-aee4-dd1c531601a1';
--> statement-breakpoint
UPDATE "boholz"."model_media" SET "sort_order" = 3 WHERE "model_id" = '8945ad8d-411e-47b2-ad56-3356399f759d' AND "media_id" = '28fca78c-9965-460c-bb79-7e24a2a43400';
--> statement-breakpoint
UPDATE "boholz"."model_media" SET "sort_order" = 4 WHERE "model_id" = '8945ad8d-411e-47b2-ad56-3356399f759d' AND "media_id" = '3807e994-7254-4f10-9504-665979b0d3e9';
--> statement-breakpoint
-- #1 converge grey pivot flags if the row pre-existed
UPDATE "boholz"."model_media" SET "is_hero" = true, "is_thumbnail" = true, "sort_order" = 0
WHERE "model_id" = '8945ad8d-411e-47b2-ad56-3356399f759d' AND "media_id" = (SELECT "id" FROM "boholz"."media" WHERE "path" = '/images/models/stadtvilla/22-157/gallery/stadtvilla-22-157-gallery-sv-157-22-0-grau.webp');
--> statement-breakpoint
-- #6 Musterhaus Fellbach contact order: Wissmann, Dittrich, Aszalós, Kober
--> statement-breakpoint
UPDATE "boholz"."location_agents" SET "sort_order" = 0, "is_primary" = true
WHERE "location_id" = '10000000-0000-0000-0000-000000000002' AND "agent_id" = (SELECT "id" FROM "boholz"."agents" WHERE "slug" = 'dieter-wissmann');
--> statement-breakpoint
UPDATE "boholz"."location_agents" SET "sort_order" = 1, "is_primary" = false
WHERE "location_id" = '10000000-0000-0000-0000-000000000002' AND "agent_id" = (SELECT "id" FROM "boholz"."agents" WHERE "slug" = 'michael-dittrich');
--> statement-breakpoint
UPDATE "boholz"."location_agents" SET "sort_order" = 2, "is_primary" = false
WHERE "location_id" = '10000000-0000-0000-0000-000000000002' AND "agent_id" = (SELECT "id" FROM "boholz"."agents" WHERE "slug" = 'istvan-aszalos');
--> statement-breakpoint
UPDATE "boholz"."location_agents" SET "sort_order" = 3, "is_primary" = false
WHERE "location_id" = '10000000-0000-0000-0000-000000000002' AND "agent_id" = (SELECT "id" FROM "boholz"."agents" WHERE "slug" = 'hagen-kober');
--> statement-breakpoint
-- #9 Vertriebsbüro Nittel contact
INSERT INTO "boholz"."agents" ("full_name", "slug", "role", "phone_number", "email")
SELECT 'Gabriella Schaffer', 'gabriella-schaffer', 'Beratung und Verkauf', '+49 176 40 90 12 69', 'g.schaffer@boholz-haus.de'
WHERE NOT EXISTS (SELECT 1 FROM "boholz"."agents" WHERE "slug" = 'gabriella-schaffer');
--> statement-breakpoint
INSERT INTO "boholz"."location_agents" ("location_id", "agent_id", "is_primary", "sort_order")
SELECT 'c8112bb1-e5d5-4736-8da0-c332727f6616', (SELECT "id" FROM "boholz"."agents" WHERE "slug" = 'gabriella-schaffer'), true, 0
WHERE NOT EXISTS (
  SELECT 1 FROM "boholz"."location_agents"
  WHERE "location_id" = 'c8112bb1-e5d5-4736-8da0-c332727f6616' AND "agent_id" = (SELECT "id" FROM "boholz"."agents" WHERE "slug" = 'gabriella-schaffer')
);
--> statement-breakpoint
-- #2 (stadtvilla-22-166 heading) + #10 de-hyphenated descriptions (23 models)
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Ein einzigartiger Ausblick. Das verschafft Ihnen dieser grandiose Bungalowentwurf. Seine bis zum Boden reichenden, großen Fensterfronten lassen nicht nur Sonnenlicht in den Wohnbereich hinein, sondern geben auch einen wunderbaren Ausblick in den Garten. Alternativ kann auch eine Einliegerwohnung oder ein separat abgetrennter Homeoffice Bereich eingeplant werden. Die variablen Anpassungsmöglichkeiten machen dieses Hauskonzept so besonders.' WHERE "slug" = 'bungalow-22-134';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Wohnen auf einer Ebene. Der klassische Baustil dieses Bungalowentwurfes bietet ein Raumgefühl auf einer Fläche, ganz ohne Hindernisse und Stufen. Die kurzen Wege innerhalb der Raumaufteilung und die offenen Wohnbereiche kombinieren intelligente Lösungen für den Alltag. Mit rund 45 m² bietet der helle Wohn-, Ess- und Kochbereich das Highlight dieses Klassikers. Ein Schlafzimmer mit angrenzendem Badezimmer sowie einer eigenen Ankleide lässt kaum Wünsche offen. Im Eingangsbereich findet sich auf der linken Seite der durchdacht eingeplante Arbeitsbereich, der auch kurzerhand als Gästezimmer umfunktioniert werden kann. Den perfekten Rundumblick erhalten Sie mit der überdachten Terrasse, der den Wohn- und Essbereich umschließt.' WHERE "slug" = 'bungalow-22-149';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Das Doppelhaus für gehobene Ansprüche. Das Erdgeschoss überzeugt auf ganzer Linie. Mit seinem Wohn- und Essbereich auf 42 m² Wohnfläche und zwei eingeplanten Terrassenausgängen bietet es genug Platz, um der Mittelpunkt des Alltags zu werden. Ein zum Gästezimmer änderbares Arbeitszimmer wie auch der große Haustechnikraum komplettieren den Grundriss im Erdgeschoss. Ein Obergeschoss ganz ohne störende Dachschrägen finden Sie in diesem Hauskonzept. Das Elternschlafzimmer wird ergänzt durch eine Ankleide aber auch die beiden großzügigen Kinderzimmer bieten Platz für Spiel und Spaß. Das große Familienbadezimmer lädt zum Verweilen ein.' WHERE "slug" = 'doppelhaus-28-299';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Doppelt hält besser. Dieser moderne Doppelhausentwurf besticht vor allem durch seine optische Finesse. Die dominante Eingangsüberdachung, die fließend in das Carport übergeht, verleiht diesem Grundriss geometrische Gleichheit. Egal, ob Sie mit bereits vorausgewählten Baupartnern bauen oder im Nachhinein vermieten möchten – mit diesem Konzept sind Sie flexibel. Die Wohnfläche an sich bietet mit seiner klassischen Planung den Wohn- und Essbereich im Erdgeschoss und Schlafräumen im Obergeschoss Platz für alle Familienmitglieder.' WHERE "slug" = 'doppelhaus-38-238-125';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Ein durchdachtes Konzept. Dieser Hausentwurf gibt Ihnen die Möglichkeit unter Schrägen zu wohnen, ohne sich den Kopf anzuschlagen. Der besonders hohe Kniestock ermöglicht genug Freiraum, um sich bei der Möblierung auszutoben. Eine sich vom Wohn- und Essbereich abgrenzende Küche ist in diesem Hausentwurf eingeplant und schafft damit einen perfekten Rückzugsort - egal, ob man sich dem nächsten Michelin-Stern zuwendet oder im angrenzenden Wohnzimmer seinen Lieblingsfilm ansieht. Die bodentiefen Fenster laden dazu ein, die Natur ein Stück weiter mit ins Haus zu lassen und bieten eine wunderbare Symbiose zur umliegenden Natur. Im Obergeschoss befindet sich ein überdurchschnittlich großes Elternschlafzimmer mit angrenzender Ankleide und gegenüberliegenden Kinderzimmern für mehr Privatsphäre. Ein lichtdurchflutetes großes Badezimmer lädt zum Verweilen ein. Eine auf Wunsch erhältliche Pergola oder ein Carport verleihen dem Haus äußerlich einen ganz neuen Charakter.' WHERE "slug" = 'einfamilienhaus-22-141-190';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Einfamilienhaus mit Homeoffice-Konzept – flexibel für jeden Anspruch. Durch seine geplante Homeoffice-Nutzung wird der Grundriss in Gänze bereits anders geplant. Mit viel Ruhe für die anstehende Arbeitswelt ist das Homeoffice in einem für sich liegenden, separaten Bereich im Erdgeschoss untergebracht, um selbst bei Trubel ungestört arbeiten zu können. Der zentrale Mittelpunkt des täglichen Lebens spiegelt sich im Wohn- und Essbereich wider. Die angrenzende, jedoch teilweise abgetrennte Küche bietet einen perfekten Rückzugsort. Vor allem durch die bis zum Boden reichenden Fenster wird die Wohnfläche hell erleuchtet.' WHERE "slug" = 'einfamilienhaus-22-162-190';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Flexible Nutzungsmöglichkeiten dank Einliegerwohnung. Ob Bürofläche für zuhause, als Apartmentlösung für die Großeltern oder auch die eigenen Kinder ist dieses Konzept offen für Gestaltungsmöglichkeiten. Mit einem zusätzlich eingeplanten Raum besticht die 125 m² große Hauptwohnung vor allem durch eine großzügige Aufteilung der einzelnen Bereiche wie den beiden Kinderzimmern und dem Elternschlafzimmer. Schon heute nachhaltig an morgen denken. Durch die Solaranlage mit Stromspeicher und Ladestation sind Sie bestens für die Zukunft vorbereitet.' WHERE "slug" = 'einfamilienhaus-22-173-190';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Ungestörtes Arbeiten von zuhause aus. Mit unseren ideenreichen Entwürfen ist auch das zukünftig kein Problem. Dieser großzügige Hausentwurf bietet auf 161 m² Wohnfläche alles, was eine junge und moderne Familie braucht. Imposante Kinderzimmer und ein großzügiges Schlafzimmer mit Ankleide und Direktzugang zum angrenzenden Badezimmer. Raffinierte Lösungen bieten sich auch im Erdgeschoss dieses an Kreativität nicht zu übertreffenden Entwurfes. Vom angrenzenden Hauswirtschaftsraum mit Trennung zum Wohnraum und inkludierter Eingangsüberdachung bis hin zur eingeplanten Speisekammer - dieser Entwurf lässt keine Wünsche offen.' WHERE "slug" = 'einfamilienhaus-25-168-190';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Der Familien-Allrounder. Dieser moderne Einfamilienhaus-Entwurf bietet alles, was eine Familie heutzutage benötigt. Zwei große Kinderzimmer sowie ein großes Badezimmer optimieren diesen familienfreundlichen Grundriss. Das angrenzende Ankleidezimmer mit eigenem Badezimmerzugang lässt keine Wünsche offen. Das im Erdgeschoss liegende Gästezimmer kann auch als Arbeitszimmer umfunktioniert werden. Der herausstechende Carport passt sich optisch perfekt in die Bauweise des Hauses mit ein und verleiht dem Ganzen eine unverkennbare Eleganz.' WHERE "slug" = 'einfamilienhaus-28-182-170';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Flexible Nutzungsmöglichkeiten dank Einliegerwohnung. Ob Bürofläche für zuhause, als Apartmentlösung für die Großeltern oder auch die eigenen Kinder ist dieses Konzept offen für Gestaltungsmöglichkeiten. Mit einem zusätzlich eingeplanten Raum besticht die 125 m² große Hauptwohnung vor allem durch eine großzügige Aufteilung der einzelnen Bereiche wie den beiden Kinderzimmern und dem Elternschlafzimmer. Schon heute nachhaltig an morgen denken. Durch die Solaranlage mit Stromspeicher und Ladestation sind Sie bestens für die Zukunft vorbereitet.' WHERE "slug" = 'einfamilienhaus-28-194-170';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Akzente setzen ist das Stichwort. Dieses Haus besticht nicht nur durch seine moderne wie auch zeitlose Bauweise, sondern auch durch seine optische Abgrenzung. Ein offener Wohn- und Essbereich mit offener Küche ist der perfekte Ort für Familienabende. Von Spieleabend bis zum Festmahl sind der Belebung dieser Räume keine Grenzen gesetzt. Das eingeplante Gäste- oder auch Arbeitszimmer erschafft neue Möglichkeiten der räumlichen Nutzung und schafft einen Rückzugsraum im unteren Wohnbereich. Als Highlight dient in diesem schmucken Wohntraum der Elternbereich mit Ankleidezimmer. Um auch den Kleinsten den größten Platz bieten zu können, bestechen die beiden Kinderzimmer mit einer jeweiligen Größe von 13 m². Eine Wellness-Oase unter dem heimischen Dach? Mit diesem Entwurf ist das möglich. Er glänzt vor allem durch das große Hauptbadezimmer im Obergeschoss. Durch den optionalen Carport in Verlängerung zum Vordach des Hauseingangs bieten sich kurze Wege, die Sie vor Wind und Wetter schützen.' WHERE "slug" = 'einfamilienhaus-35-146-150';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Ein harmonisches Miteinander. Das ist es, was sich jede Familie wünscht. Mit unserem Hausentwurf bieten wir hierfür gleich vier großzügig geschnittene Kinderzimmer an. Die zeitlose und doch moderne Bauweise verleiht diesem Grundriss seinen Charme. Mit seinen beiden bodentiefen Fenstern sorgt dieser für optimalen Lichteinfall. Intelligent durchdacht befindet sich das Arbeitszimmer im Erdgeschoss in der Nähe des Hauseingangs. Alternativ kann auch eine Einliegerwohnung oder ein separat abgetrennter Homeoffice-Bereich eingeplant werden. Die variablen Anpassungsmöglichkeiten machen dieses Hauskonzept so besonders.' WHERE "slug" = 'einfamilienhaus-35-181-150';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Wir haben es optimiert - jetzt mit mehr Platz. Aus rund 117 m² Wohnfläche haben Sie nun noch mehr Möglichkeiten sich frei zu entfalten. Im Erdgeschoss sind vor allem die familiäre Nähe und die Kommunikation der Mittelpunkt der Wohnfläche. Im Obergeschoss bieten sich Rückzugsmöglichkeiten für jeden Einzelnen. Verlorener Platz, wie beispielsweise durch große, raumnehmende Flure, werden Sie in diesem Haus nicht finden. Wir optimieren den Wohnraum Ihres täglichen Wohnbedarfs und maximieren so Ihr Wohngefühl in Ihrem neuen Zuhause.' WHERE "slug" = 'einfamilienhaus-38-128-125';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Klassische Architektur. Das bietet dieser Hausentwurf mit seinen bodentiefen Fenstern mit rundum Blick und sonnigen Räumen. Mit seinem offenen und großzügigen Grundriss bietet dieser Einfamilienhausentwurf Platz für allerhand Gestaltungsmöglichkeiten. So zum Beispiel mit seiner offenen Wohnküche, die auf unschlagbaren 41 m² der ganzen Familie Platz bietet. Durch die sich im Obergeschoss befindlichen Kinderzimmer mit ihrer durchdachten Planung, ist für jeden genügend Platz. Auch für die Eltern. Ein Haus für die Familie.' WHERE "slug" = 'einfamilienhaus-38-138-125';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Aller guten Dinge sind Drei. In diesem Fall – drei Giebel! Ob offene Galerie oder eine Leseecke - Ihren gestalterischen Fähigkeiten lässt dieser Hausentwurf freien Raum. Mit einer Grundwohnfläche von 41 m² im Erdgeschoss, auf denen sich Wohnzimmer, Esszimmer und Küche befinden, lassen sich gemeinsame Abende jetzt schon erträumen. Auch ein Gäste- bzw. Arbeitszimmer findet hier seinen Platz. Auf dem Balkon verweilen - das hört sich nicht nur traumhaft an, sondern ist mit diesem eleganten und zeitgenössischen Wohntraumbeispiel möglich! Darf es ein Tupfen Farbe sein? Durch sein farblich abgesetztes Zwerchhaus fällt dieses modern geschnittene und designte Haus in Ihrer Nachbarschaft jedem ins Auge.' WHERE "slug" = 'einfamilienhaus-45-139-75';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Alles unter einem Dach – mit unserem Generationenkonzept! Mit seinen beiden Wohnungen im Ober- und Erdgeschoss ist dieser Hausentwurf auf alles vorbereitet, was das Leben so bietet. Mit einer sich über zwei Geschosse erstreckenden Hauptwohnung glänzt dieser Grundriss vor allem mit seiner großzügigen Aufteilung. Auf vollen 44 m² Wohnfläche befinden sich die offene Küche wie auch der Wohn- und Essbereich. Durch die bodentiefen Fenster werden die hellen Räume mit Licht durchflutet und geben den perfekten Blick ins Grüne. Der Elternbereich im Obergeschoss überzeugt vor allem durch das eigene Badezimmer wie auch das Ankleidezimmer. Ausgestattet mit zwei großen Kinderzimmern mit eigenem Badezimmer wird dieser Hausentwurf vollends abgerundet.' WHERE "slug" = 'generationenhaus-28-264-160';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Für die moderne Familie. Mit einer Wohnfläche von rund 165 m² und seinen intelligenten Details bietet dieser schicke Hausentwurf alles, was eine moderne Familie zum heutigen Leben benötigt. Mit einer Doppelgarage, durch welche man direkt in den Hauswirtschaftsraum der Küche gelangt, verringern sich Laufwege erheblich. Ausgestattet mit zwei weiteren Räumen auf beiden Ebenen ermöglicht dieser Kubus individuelle Nutzungsmöglichkeiten – ob als Gäste- oder Arbeitszimmer. Durch sein großzügiges Vollgeschoss passt sich dieser Entwurf Ihren Bedürfnissen an. Mit einem Schlafzimmer mit angrenzendem Ankleidezimmer sowie zwei hellen Kinderzimmern lässt er keine Wünsche offen. Auch äußerlich ist dieser Kubus ein wahrer Hingucker. Durch seine moderne und gradlinige Form sowie der abgesetzten Holzfassade und dem überdachten Eingangsbereich können Bauherrinnen und Bauherren ein deutliches Zeichen für zeitgenössisches Bauen setzen.' WHERE "slug" = 'kubus-0-166';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Individuelle Moderne – außen und innen. Einzigartig wie jede Bauherrin und jeder Bauherr ist auch dieser Hausentwurf. Durch seine außergewöhnliche und markante Gestaltung mit dem 23 m² großen Balkon ist diese Kubusvilla ein wahrer Augenschmaus. Mit einer Fläche von beinahe 190 m² bietet dieser Entwurf großzügig geschnittene und helle Wohnräume. Der Grundriss wird auch den größten Ansprüchen gerecht. Selbstverständlich kann dieser Hausentwurf mit einer Garage oder einem Carport ergänzt werden.' WHERE "slug" = 'kubus-0-190';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Entspannung an der frischen Luft. Das bietet dieser Kubusentwurf mit seinen drei überdachten Balkonen und der teilüberdachten Terrasse. Er überzeugt vor allen Dingen durch den riesigen Küchenbereich nebst Essplatz und Direktzugang zur Sonnenterrasse. Vervollständigt wird das Erdgeschoss durch ein großzügiges Badezimmer sowie dem Schlafzimmer mit Ankleide. Das Obergeschoss besticht durch den lichtdurchfluteten Wohnbereich und bietet nicht nur zwei Kindern, sondern auch noch Gästen Platz. Auch das Arbeiten von zuhause ist dank des eingeplanten Arbeitszimmers möglich. Im oberen Geschoss findet sich zudem ein großzügig geplantes Badezimmer wieder.' WHERE "slug" = 'kubus-0-278';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Ein eleganter Auftritt mit zwei Vollgeschossen. Das bietet unser Stadtvillen-Entwurf mit Walmdach für Sie. Durch sein großes und offenes Wohnerlebnis bietet dieser Hausentwurf das optimale Wohngefühl und dennoch genug Platz für ein Arbeits- oder Gästezimmer. Ein zurückgesetzter Balkon fungiert zeitgleich als Überdachung für den Hauseingang. Auf der gegenüberliegenden Hausseite wird dieser durch einen französischen Balkon ersetzt und schafft ein zusätzliches Naturgefühl. Privatsphäre erfahren die Eltern im Obergeschoss mit einem großzügigen Elternbereich. Das angrenzende Badezimmer wie auch das Ankleidezimmer bieten das Rund-um-Sorglos-Paket für alle, die etwas mehr Luxus wünschen. Auch für die Kinder wurde mitgedacht. Von beiden Kinderzimmern aus zugänglich befindet sich ein eigenes Badezimmer.' WHERE "slug" = 'stadtvilla-18-140';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Mondän und Modern – dank farblich abgesetztem Konzept. Ein lichtdurchfluteter Wohn- und Essbereich zieht sich entlang der gesamten Gartenseite. Sinnvoll ergänzt wird der Grundriss im Erdgeschoss durch ein Arbeitszimmer. Zwei gleich dimensionierte Kinderzimmer im Obergeschoss sowie ein großes Familienbadezimmer und ein sich über 24 m² erstreckender Elternbereich mit eigenem Ankleideraum bietet ein großzügiges Wohngefühl in der oberen Etage. In der optionalen Doppelgarage finden neben den Fahrzeugen auch Fahrräder oder Gartengeräte ihren Platz.' WHERE "slug" = 'stadtvilla-22-157';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Die Stadtvilla neu erleben – mit integrierter Doppelgarage und direkten Zugang in den Hauswirtschaftsraum. Dieser Hausentwurf erfreut sich stetig wachsender Beliebtheit. Mit seinen zwei Vollgeschossen und dem eleganten und modern wirkenden Außenauftritt begeistern sich immer mehr Baufamilien von dieser traumhaften Wohnvariante. Eine perfekt auf die Bedürfnisse einer Familie zugeschnittene Grundwohnfläche von knapp 165 m² lässt keine Wünsche mehr offen. Die integrierte Doppelgarage mit direktem Zugang in den Hauswirtschaftsraum, der großzügige Koch-, Wohn- und Essbereich wie auch das Schlafzimmer mit Ankleideraum sind nur einige der Vorteile, die dieser Hausentwurf für Familien mit sich bringt. Mit zwei zusätzlichen Räumen, zum Beispiel für das Arbeiten von zuhause aus oder das Beherbergen von Gästen, passt sich diese Stadtvilla sämtlichen Anforderungen an.' WHERE "slug" = 'stadtvilla-22-166';
--> statement-breakpoint
UPDATE "boholz"."house_models" SET "description" = 'Einfach zum Verlieben. Durch seine vielseitige Nutzung dank der eingeplanten Einliegerwohnung gibt dieser Hausentwurf mehrere Wohnmöglichkeiten hervor. Mit einer Grundwohnfläche von 125 m² bietet die Hauptwohnung mit zwei Kinderzimmern und einem großzügigen Elternbereich sowie einem weiteren Raum für ein eigenes Homeoffice, einen Hobbyraum oder ein Gästezimmer jede Menge Raum für die täglichen Bedürfnisse. Durch seine optional zur Straßenseite hin farbig gestaltete Außenfassade setzt diese Stadtvilla auch optisch einen klaren Akzent.' WHERE "slug" = 'stadtvilla-22-173';
