export const ROUTES = {
  home: "/",
  houses: "/hauser",
  house: (slug: string) => `/haus/${slug}`,
  promise: "/unser-versprechen",
  yourHouse: "/dein-zuhause",
  aboutUS: "/uber-uns",
  news: "/news",
  newsArticle: (slug: string) => `/news/${slug}`,
  contact: "/kontakt",
  onsite: "vor-ort-beratung",
  impressum: "/impressum",
  datenschutz: "/datenschutz",
  cookies: "/cookies",
  landing: {
    uebersicht: "/landing/uebersicht",
    bungalow: "/landing/bungalow",
    mehrfamilien: "/landing/mehrfamilien",
  },
} as const;
